Update azp-job-wheels.yaml

diff --git a/templates/azp-job-wheels.yaml b/templates/azp-job-wheels.yaml
--- a/templates/azp-job-wheels.yaml
+++ b/templates/azp-job-wheels.yaml
@@ -140,9 +140,20 @@ jobs:
       # Copy file in & Inject SSH files
       docker cp "${data_path}/." "${container_id}:/data"
       docker cp -a .ssh/ "${container_id}:/root/.ssh"
-      
+
       # Create wheels
-      docker start -a "${container_id}"
+      # Use retry on error unlike 109
+      for i in {1..3}; do
+        docker start -a "${container_id}"
+        return_val=$?
+
+        if [ ${return_val} -ne 0 ] && [ ${return_val} -ne 109 ]; then
+          continue
+        fi
+        break
+      done
+
+      exit ${return_val}
     displayName: 'Run wheels build'
   - script: |
       docker rm -f "${{ parameters.jobName }}-$(Build.BuildId)-$(Build.BuildNumber)-$(buildArch)"
